<a href="https://colab.research.google.com/github/CodeX-Addy/Machine_Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [ ]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
## check the shape of the array
arr.shape

(3, 5)

In [ ]:
#Access the elements of the array
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [ ]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [ ]:
#Reshaping the array
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr1=np.arange(0,10).reshape(2,5)

In [ ]:
arr2=np.arange(0,10).reshape(2,5)

In [ ]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#Random Distribution
np.random.rand(3,3)

array([[0.764817  , 0.2568677 , 0.94119137],
       [0.64446991, 0.10903554, 0.50048763],
       [0.72578399, 0.74076162, 0.77712123]])

In [ ]:
arr_ex=np.random.randn(4,4)

In [ ]:
arr_ex

array([[ 0.25877241,  0.70398826, -0.81926615, -0.36253845],
       [-0.61803992, -1.18479039,  0.45438434, -0.00392489],
       [-1.54655261,  1.04846612,  0.2401826 , -3.31650973],
       [-1.10666699, -0.32925841,  1.35569629, -1.47819742]])